exclude: ".git"
default_stages: [pre-push]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]
      - id: check-yaml
      # - id: no-commit-to-branch
      #   args: [-b, master, -b, production, -b, staging]

  - repo: local
    hooks:
      - id: mix-precommit
        name: "elixir: mix precommit"
        entry: mix precommit
        language: system
        pass_filenames: false
        files: \.exs*$
